### ISSUE TITLE
set_geometry error with unhasable type Point

### ISSUE THREAD

**Issue by BENR0** [geopandas/dask-geopandas#117]
When I try to set the geometry on a points geodataframe as shown in the readme I get a `TypeError: unhashable type: Point`.

I am using:
 - pandas 1.3.3
 - geopandas 0.9.0
 - dask-geopandas 0.1.0 (installed from master branch last week)
 - dask 2021.7.2
 - pygeos 0.10.2

# Example:
```Python
import numpy as np
import pandas as pd
import dask.dataframe as dd
import dask_geopandas

n = 1000
X = np.random.random((n, 2))
X[:, 0] = 360 * X[:, 0] - 180
X[:, 1] = 170 * X[:, 1] - 85
df = pd.DataFrame(X, columns=['lon', 'lat'])

ddf = dd.from_pandas(df, npartitions=2)
ddf = dask_geopandas.from_dask_dataframe(ddf)
ddf = ddf.set_geometry(dask_geopandas.points_from_xy(ddf, 'lon', 'lat'))
```

Just as a side note: I tried to work around it using:
```Python
from pygeos.lib import points

ddf["geometry"] = points(ddf[["lon", "lat"]].values)
ddf = dask_geopandas.from_dask_dataframe(ddf)
ddf = ddf.set_geometry("geometry")
```

Which works if I do not use a `dask.distributed` cluster otherwise I get a deserialization issue (I use `pygeos.lib.points` here because the conveniance function to create points in pygeos executes eagerly). This seems to be a special issue with points though because the second example works for `pygeos.box` geometries.

**Comment by jorisvandenbossche** [comment]
Thanks a lot for the report @BENR0 
It seems like I broken this use case in https://github.com/geopandas/dask-geopandas/pull/101, and we didn't have tests for it ..

**Comment by BENR0** [comment]
I have looked into it a little before creating the issue but I came to the conclusion that I have to little knowledge about the internals to come up with a quick fix. Anyway if there is something I can do to help fix this let me know.

**Comment by jorisvandenbossche** [comment]
I already opened a PR with a fix -> #118 !

(and using dask-geopandas, and giving feedback / reporting issues is already super helpful!)

**Comment by BENR0** [comment]
Thanks, will try it out later. Just stumbled over dask-geopandas the other day while searching for working with geopandas and large datasets. I really like it and appreciate all the work you guys are doing to push this forward.

Not directly related (maybe should open an issue?): I was wondering if something kind of like the `by` option in `merge_asof` would be interesting in spatial joins? I guess this would be rather complex and is not exclusive to dask-geopandas but also geopandas. But I think this would be nice for example when working with spatial timeseries.

**Comment by martinfleis** [comment]
>  I was wondering if something kind of like the by option in merge_asof would be interesting in spatial joins?

Can you open an issue on that in the main https://github.com/geopandas/geopandas repo?
