### ISSUE TITLE
clip calls wrong clip function

### ISSUE THREAD

**Issue by kai-tub** [geopandas/dask-geopandas#127]
Hey all.

I am loving the work on this project!
I've stumbled upon a bug and wanted you to let you know about it.
I don't know if it is actually worth "fixing".
If one calls `.clip` on a geopandas dask dataframe object, the dask clip function (clipping values between `min/max` is called)

To reproduce:

```python
import geopandas
import dask_geopandas

path_to_data = geopandas.datasets.get_path("nybb")
gdf = geopandas.read_file(path_to_data)
ddf = dask_geopandas.from_geopandas(gdf, npartitions=2)
ddf.clip(gdf.geometry[0])
```

**Comment by martinfleis** [comment]
Hi, this is not a bug strictly speaking. But it is surely something worth fixing. We have introduced `clip` as a method on geopandas in the last release and this API change has not propagated to dask-geopandas yet. The same applies to `sjoin` and `overlay`, in fact.

We should expose `sjoin` and `clip` as methods here as well, it just hasn't been done yet.

**Comment by kai-tub** [comment]
I see.
I am quite interested in the development of the package and would like to contribute a bit if possible.
I have some experience with Dask and _use_ Geopandas, but am not too familiar with the internals.
Maybe some issues could be marked as _Good first issue_?

I know this is an alpha level library, but maybe there are some small tasks I can help out with :)

**Comment by martinfleis** [comment]
@kai-tub Sorry for a slow response! 

Any help is welcome, I am just not sure if there's a lot _good first issues_ at the moment. One that comes to my mind is mentioned in #130:

> `covers` and `covered_by` are 2 missing predicates that should be trivial to add here
