### ISSUE TITLE
Limit amount of arrow spec warnings

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#138]
Currently, saving to a parquet file prints one warning about the initial implementation of parquet format per partition. And that can be a lot of warnings. It would be great if we could catch them and raise it only once.

(Or finish geo-arrow-spec so we don't need it anymore :)).

**Comment by jorisvandenbossche** [comment]
Yes, we could certainly reduce that. 

Now, I think we can maybe also simply remove the warning in geopandas. While I wouldn't consider the spec stable, I think at this point it is already used enough to say that we will keep some backcompat layer in geopandas to be able to read files written with the current pandas, even if the metadata spec would still change? 
If we will do that, I think it should be OK to remove the warning? (of course if other libraries would start supporting such parquet files after a spec change, that might give problems that way. But the spec has a version, so they could check for that)

**Comment by martinfleis** [comment]
> at this point it is already used enough to say that we will keep some backcompat layer in geopandas to be able to read files written with the current pandas, even if the metadata spec would still change?

I think that this is a reasonable solution now. I've seen parquets in wild so it is only fair to keep backwards compatibility.

> If we will do that, I think it should be OK to remove the warning?

I think so, yes. We can still mention it in a docstring. 

> (of course if other libraries would start supporting such parquet files after a spec change, that might give problems that way. But the spec has a version, so they could check for that)

I don't think that is necessarily a geopandas issue then.

**Comment by martinfleis** [comment]
Closed by https://github.com/geopandas/geopandas/pull/2327
