### ISSUE TITLE
Parallel Dissolve Bottleneck

### ISSUE THREAD

**Issue by eljirg** [geopandas/dask-geopandas#143]
Hi,

I am trying to use dissolve to combine a large number of polygons (68000 pieces) with the sample code in **https://github.com/geopandas/dask-geopandas/blob/main/notebooks/dissolve.ipynb**

The polygons came from a segmentation model doing predictions from small parts of a big image. I tried to combine pieces of the model prediction to stitch them back and overlay them to the original big image (30000x20000 px).

During the process, CPU utilization was closely monitored. At the beginning of the dissolve process, the whole CPU seems to be fully utilized, however, after a while, it only utilizes a single CPU. The time when the whole CPU is in use is quite short (around 3-5 minutes), however, after that single CPU is running it would take around 5 hours to finish the dissolve.

My guess is there is a bottleneck when the final result is being merged (CMIIW).

This is how I run it, as a note these polygons only have a single group.
```
import geopandas as gpd
import dask_geopandas as dgpd

df = gpd.read_file('polygons.shp')
ddf = dgpd.from_geopandas(df, npartitions=20)
dissolved_nparts = ddf.dissolve(split_out=20)
res = dissolved_nparts.compute()
```

Am I doing something wrong? 
If this is expected is there a way to optimize the last process? 

That aside, thank you for your work!

**Comment by martinfleis** [comment]
Hi,
My assumption is that the `ddf` is not sorted spatially, hence the result of the within-partition dissolve is a largely discontinuous MultiPolygon. When these are then moved together to a single chunk to do the across-partition dissolve, it is a very expensive operation. Note that since you have only one group, the final step will always use a single thread and `split_out` keyword does not have an effect (you will have only a single partition anyway).

Try spatial sorting and let us know the effect. We can then look into other potential speedups.

```py
import geopandas as gpd
import dask_geopandas as dgpd

# since your data frame fits in the memory, it is more efficient to do it before converting to dask, hence this trick (for now)
from dask_geopandas.hilbert_distance import _hilbert_distance

df = gpd.read_file('polygons.shp')

# this sorts data spatially
df = df.set_index(_hilbert_distance(df, df.total_bounds, p=10))

ddf = dgpd.from_geopandas(df, npartitions=20)
dissolved_nparts = ddf.dissolve()
res = dissolved_nparts.compute()

**Comment by eljirg** [comment]
Hi @martinfleis,

Thank you for your suggestions. Using the sorting trick the process is sped up!
I have tried it several times and all can be done consistently within +- 40 minutes.

One curious thing is that I made a slight mistake in the beginning, instead of assigning npartitions using the number of partitions that I wanted, I put -2 thinking it would utilize all except two CPUs (mixed things up with joblib's Parallel) and it take 11 hours to finish. This being the case am I correct to assume that the most optimal npartitions is to match the number of available CPUs?

Thank you for all the help

**Comment by martinfleis** [comment]
>  the most optimal npartitions is to match the number of available CPUs?

If you can safely assume that all your partitions have the same number of geometries of similar complexity. If that varies for some reason (e.g. chunk subnational boundaries per state), it may be better to have more partitions that workers as it balances different complexity of union within individual partitions. In your case, I think that npartitions==n_cpu is a reasonable choice.

**Comment by jorisvandenbossche** [comment]
Using npartitions=n_cpu also assumes that all your data fits in memory (and if that's the case, that number of partitions seems indeed a good choice). Since you start from an in-memory GeoDataFrame read with geopandas, that's of course the case here.  
But in general, a typical case to use more partitions is when you have a larger dataset and only load a subset of the partitions into memory at the same time.

**Comment by eljirg** [comment]
I am currently trying with more polygons (100000+) and the process become a whole lot longer.

I tried an experiment which is to hard split the area into 36 equal grids and work to dissolve one grid at a time.
This split is to help limit the area scope (which I think would help the process, CMIIW).

One thing that I found is that there is a grid that takes way longer than the other grids to dissolve. I'm using the same method above to do the dissolve and spatial sorting, just working one grid at a time.

Grid 1:
Total polygons: 7215
Time to finish dissolve: 17.9 seconds
Resulting Multipolygon length: 69

Grid 2:
Total polygons: 6881
Time to finish dissolve: **1732.8 seconds**
Resulting Multipolygon length: 47

I did some investigations on these two grids.
Polygons on Grid 1:
data type: shapely.geometry.polygon.Polygon (all same)
is_valid: 5565 (True), 1650 (False)
area: 0.0 (minimum), 61.8 (maximum)

Polygons on Grid 2:
data type: shapely.geometry.polygon.Polygon (all same)
is_valid: 5363 (True), 1518 (False)
area: 0.0 (minimum), 60.7 (maximum)

Is there something that might severely slow down union process? Something like self-intersection, number of vertex that constitutes the polygon?

Currently I'm trying to investigate more on why the polygons in grid 2 takes 100x times longer to dissolve, if you can give some insight on what could be the cause, it will be very appreciated.

**Comment by martinfleis** [comment]
@eljirg Can you share these two grids?

**Comment by eljirg** [comment]
@martinfleis I am currently trying to get some approvals to be able to share them, hopefully, it can go through.

In the meanwhile any suggestion of what can be investigated?

**Comment by martinfleis** [comment]
> In the meanwhile any suggestion of what can be investigated?

Not really, I am as puzzled as you are. I want data to be able to profile it with snakeviz or py-spy to understand what is causing the difference. It may be that you uncovered some issue deep in GEOS that just bubbles up in here. 

Merging 6881 polygons should never take half an hour, not even in a single thread.

**Comment by eljirg** [comment]
The issue seems to be resolved by creating a new environment and reinstalling the packages. Now the process is done in under a minute.

**Comment by eljirg** [comment]
I see, that might be the case. Not sure if this will help or not but this is the GDAL version on each environment.

Previous environment: GDAL 3.0.2
Current environment: GDAL 3.4.1

**Comment by martinfleis** [comment]
It is not GDAL but GEOS version that could make a difference in this case.

**Comment by eljirg** [comment]
Ah sorry, mistook the two. Both environment are on GEOS 3.8.0
Checked with `$geos-config --version`
