### ISSUE TITLE
Handling of empty geometries in Hilbert/Morton distance methods

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/dask-geopandas#146]
Currently the functionality "works" (i.e. doesn't break down) when empty geometries are present:

```
>>>s = geopandas.GeoSeries.from_wkt(["POINT (1 2)", "POINT (2 1)", "POLYGON EMPTY", "POINT (10 10)"])
>>> ds = dask_geopandas.from_geopandas(s, npartitions=1)
>>> ds.hilbert_distance().compute()
0     16691136
1      5509098
2            0
3    715827882
Name: hilbert_distance, dtype: uint32

```

but so empty geometries get filled in with 0. 

Is this OK? Or do we want to raise an error instead if there are empty geometries?

When using this in a context of spatial shuffling, this would mean that all empty ones end up in the same partition (which seems OK if for some reason you want to keep those empty geometries)

**Comment by martinfleis** [comment]
I would raise. It is _okay_ within the shuffling but it is on okay to return a value. 0 has a spatial meaning and we shouldn't assign it to a geometry that does not lie in the corner of the bounds.

**Comment by jorisvandenbossche** [comment]
This is a case where it would be an advantage to have this implemented by GEOS, so it can check this empty-ness on the fly. We will have to do a `geometries.is_empty.any()` at the beginning of the implementation, I suppose?

**Comment by martinfleis** [comment]
That is not very expensive (assuming pygeos here), is it? I don't there's any other way

**Comment by brendan-ward** [comment]
Agree that raising an exception for Hilbert/Morton curve distances (also Geohash?) for empty geometries seems best, and is line with what I was thinking if this gets added to GEOS.  They are not something you can ordinate on the curves.
