### ISSUE TITLE
Guidelines for contributing

### ISSUE THREAD

**Issue by alex-translation** [geopandas/dask-geopandas#183]
Hello,

I'm loving using this project, and would love to contribute to it. The [feature parity post](https://github.com/geopandas/dask-geopandas/issues/130) seems like a great place to start.

And it seems like the [guide for contributing to GeoPandas](https://geopandas.org/en/stable/community/contributing.html) largely applies here as well.

Are there any substantial changes to those docs, either the list of features or the contributing guidelines? Edit: Especially curious about dependencies and testing that only apply here.

Thanks in advance, excited to learn.

-- --

Best,
Alex

**Comment by alex-translation** [comment]
I asked about dependencies and `pytest` because the default imports and tests led to some package version conflicts and failed tests. I resolved the imports, but have some questions about the tests. Issue #76 seems relatively simple, so I'm not sure if it's absolutely essential, but I do want to follow the contribution guidelines (all of which make sense to me).

Running `pytest` on a new conda environment leads to `10 failed, 151 passed, 4 skipped, 2 xfailed, 1009 warnings in 38.38s`. It's quite a lot of output; should I paste it all here?

**Comment by martinfleis** [comment]
> It's quite a lot of output; should I paste it all here?

Can you open an issue for that?

**Comment by alex-translation** [comment]
> > It's quite a lot of output; should I paste it all here?
> 
> Can you open an issue for that?

@martinfleis here's the issue I made for this https://github.com/geopandas/dask-geopandas/issues/184
