### ISSUE TITLE
Empty partitions cause all columns to be promoted to float

### ISSUE THREAD

**Issue by fbunt** [geopandas/dask-geopandas#190]
If one of the partitions comes back empty then `dask_geopandas` promotes all columns to float. I checked if the same thing happens with `dask.dataframe` and it does NOT. This seems to be an issue with `dask_geodataframe`, as far as I can tell. Below is an extremely simplified version of my use case. In it, I'm processing chunks of a dask array and outputting a GeoDataFrame based on the contents. If all of the values in a chunk are missing (0), then I return an empty dataframe.

```python
import dask
import dask.array as da
import dask.dataframe as dd
import geopandas as gpd
import dask_geopandas as dgpd
from shapely.geometry import Point


@dask.delayed
def chunk_to_df(x):
    values = []
    rows = []
    cols = []
    points = []
    for i in range(x.shape[0]):
        for j in range(x.shape[1]):
            if x[i, j] == 0:
                continue
            values.append(x[i, j])
            rows.append(i)
            cols.append(i)
            points.append(Point(float(j), float(i)))
    return gpd.GeoDataFrame(
        {"value": values, "row": rows, "col": cols, "geometry": points}
    )


data = da.from_array(
    np.array(
        [
            [0, 0, 1, 2],
            [0, 0, 2, 2],
            [0, 0, 1, 0],
            [0, 1, 3, 0],
        ]
    ),
    chunks=(2, 2),
)
meta = gpd.GeoDataFrame(
    {
        "value": [1],
        "row": [0],
        "col": [0],
        "geometry": Point(1.0, 1.0),
    }
)
ddf = dd.concat(
    [
        dd.from_delayed(chunk_to_df(chunk), meta=meta)
        for chunk in data.to_delayed().ravel()
    ]
)

print(ddf)
print(ddf.partitions[0].compute())
print(ddf.partitions[1].compute())
print(ddf.compute())
print(ddf.compute().dtypes)
```
### Actual Output

```python
Dask GeoDataFrame Structure:
               value    row    col  geometry
npartitions=4
               int64  int64  int64  geometry
                 ...    ...    ...       ...
                 ...    ...    ...       ...
                 ...    ...    ...       ...
                 ...    ...    ...       ...
Dask Name: concat, 16 tasks
Empty GeoDataFrame
Columns: [value, row, col, geometry]
Index: []
   value  row  col                 geometry
0      1    0    0  POINT (0.00000 0.00000)
1      2    0    0  POINT (1.00000 0.00000)
2      2    1    1  POINT (0.00000 1.00000)
3      2    1    1  POINT (1.00000 1.00000)
   value  row  col                 geometry
0    1.0  0.0  0.0  POINT (0.00000 0.00000)
1    2.0  0.0  0.0  POINT (1.00000 0.00000)
2    2.0  1.0  1.0  POINT (0.00000 1.00000)
3    2.0  1.0  1.0  POINT (1.00000 1.00000)
0    1.0  1.0  1.0  POINT (1.00000 1.00000)
0    1.0  0.0  0.0  POINT (0.00000 0.00000)
1    3.0  1.0  1.0  POINT (0.00000 1.00000)
value        float64
row          float64
col          float64
geometry    geometry
dtype: object

```

### Expected Output
All of the data columns should be integers.

```python
Dask GeoDataFrame Structure:
               value    row    col  geometry
npartitions=4
               int64  int64  int64  geometry
                 ...    ...    ...       ...
                 ...    ...    ...       ...
                 ...    ...    ...       ...
                 ...    ...    ...       ...
Dask Name: concat, 16 tasks
Empty GeoDataFrame
Columns: [value, row, col, geometry]
Index: []
   value  row  col                 geometry
0      1    0    0  POINT (0.00000 0.00000)
1      2    0    0  POINT (1.00000 0.00000)
2      2    1    1  POINT (0.00000 1.00000)
3      2    1    1  POINT (1.00000 1.00000)
   value  row  col                 geometry
0      1    0    0  POINT (0.00000 0.00000)
1      2    0    0  POINT (1.00000 0.00000)
2      2    1    1  POINT (0.00000 1.00000)
3      2    1    1  POINT (1.00000 1.00000)
0      1    1    1  POINT (1.00000 1.00000)
0      1    0    0  POINT (0.00000 0.00000)
1      3    1    1  POINT (0.00000 1.00000)
value          int64
row            int64
col            int64
geometry    geometry
dtype: object
```

**Comment by jorisvandenbossche** [comment]
@fbunt thanks for the report! Indeed, if I change your example slightly to use pd.DataFrame instead of gpd.GeoDataFrame, the `ddf.compute()` returns ints instead of floats.

Now, I am not really sure why this difference exists. For GeoPandas, the root cause is that the empty GeoDataFrame that gets created in `chunk_to_df` has float dtypes:

```
In [8]: gpd.GeoDataFrame({'value': [], 'geometry': []})
Out[8]: 
Empty GeoDataFrame
Columns: [value, geometry]
Index: []

In [9]: gpd.GeoDataFrame({'value': [], 'geometry': []}).dtypes
Out[9]: 
value        float64
geometry    geometry
dtype: object

In [10]: pd.DataFrame({'value': [], 'geometry': []}).dtypes
Out[10]: 
value       float64
geometry    float64
dtype: object
```

But you can see that this is a behaviour that gets inherited from pandas. 

So it is a bit surprising that dask.dataframe with pd.DataFrames doesn't have the same issue. I assume that in dask.dataframe, some special handling exists somewhere to avoid this issue.

**Comment by jorisvandenbossche** [comment]
OK, so it seems that when finalizing the `compute()`, dask calls `__dask_postcompute__` (which for a dask dataframe does the concat of all partitions).

It seems that we override this in dask-geopandas:

https://github.com/geopandas/dask-geopandas/blob/5b49377352658e15c34cb38a43b18fcc8f833ccb/dask_geopandas/core.py#L64-L65

https://github.com/geopandas/dask-geopandas/blob/5b49377352658e15c34cb38a43b18fcc8f833ccb/dask_geopandas/core.py#L28-L34

While this `finalize` function in upstream dask is a bit more advanced:

https://github.com/dask/dask/blob/0f5914401441d438321250c29db5a59d62afd5ef/dask/dataframe/core.py#L106-L129

More specifically, it filters out empty partitions, exactly to avoid those dtype issues as you reported.

We should check if we can just remove our implementation, or update it to also filter out empty partitions.

**Comment by fbunt** [comment]
Thanks for looking at this!

**Comment by fbunt** [comment]
Thank you again for digging into this. I have added some code to the end of my partition function to check for an empty dataframe and then force type consistency. I didn't realize that the default for empty columns was the float dtype.

**Comment by jorisvandenbossche** [comment]
Indeed, ensuring type consistency in your delayed function that generates the GeoDataFrame is probably the best option.

I did open https://github.com/geopandas/dask-geopandas/pull/191 that removes our custom `__dask_postcompute__`, which would indirectly solve your issue as well (but still fixing the types at the source is probably good practice anyway).
