### ISSUE TITLE
Create Dask GeoDataFrame from wkt string

### ISSUE THREAD

**Issue by FlorisCalkoen** [geopandas/dask-geopandas#208]
I'm trying to load geometries from wkt.strings stored in a `dask.Dataframe` . I tried both in native `dask` and `dask_geopandas`, but the libraries seem not to be able to deal with wkt strings. Since the `dask_geopandas` community is probably more familiar with this type of issue, I thought I could better raise it here. 

Please find below a toy script with some things I've tried. 

```[python]
import dask.dataframe as dd
import dask_geopandas
import numpy as np
import shapely


def point():
    return shapely.geometry.Point(np.random.randint(low=0, high=90, size=2))


df = pd.DataFrame([wkt.dumps(point()) for i in range(100)], columns=["geometry"])
ddf = dd.from_pandas(df, npartitions=4)
# ddf.compute().geometry.apply(wkt.loads)  # runs fine
# ddf.geometry.apply(wkt.loads)  # raises ParseException: Unknown type: 'FOO'


dask_geopandas.from_dask_dataframe(ddf, geometry="geometry")  # TypeError("Input must be valid geometry objects: {0}".format(geom))


def partition_wrapper(df):
    df.geometry = df.geometry.apply(wkt.loads)
    return df

dask_geopandas.from_dask_dataframe(ddf).map_partitions(partition_wrapper)  # TypeError("Only str is accepted.")
```

What would be the suggested work around? Or should a functionality to load from wkt strings become available in `dask_geopandas`?

**Comment by jorisvandenbossche** [comment]
For the case of x / y columns, we have an example in the docs like:

```
import dask.dataframe as dd
import dask_geopandas

ddf = dd.read_csv('...')

ddf = ddf.set_geometry(
    dask_geopandas.points_from_xy(ddf, 'latitude', 'longitude')
)
```

We should probably add `dask_geopandas.from_wkt/from_wkb` functions as well, so you can do something similar when starting from a WKT / WKB column.

For now, I think the best work-around is the `map_partitions` that you are already using, but simplified a bit by using geopandas' `from_wkt` (which will also be faster) on that column:

```
In [25]: ddf["geometry"].map_partitions(geopandas.GeoSeries.from_wkt, meta=geopandas.GeoSeries([]))
Out[25]: 
Dask GeoSeries Structure:
npartitions=4
0     geometry
25         ...
50         ...
75         ...
99         ...
dtype: geometry
Dask Name: from_wkt, 12 tasks
```

We need to pass `meta` in this case, because otherwise dask's inference of the output dtype fails.

That's probably also the reason why `ddf.geometry.apply(wkt.loads)` is failing.

**Comment by FlorisCalkoen** [comment]
Thanks! I think having a function `dask_geopandas.from_wkt/from_wkb` would be great.

Coming back to the workaround. I'm now calculating it like this: 

```
gddf = dask_geopandas.from_dask_dataframe(
    ddf,
    geometry=ddf["geometry"].map_partitions(
        gpd.GeoSeries.from_wkt, meta=gpd.GeoSeries([])
    ),
)
gddf = gddf.set_crs(4326)
gdf = gddf.compute()  
gdf.sample(10).explore()  # correct
```

This works as expected for a small sample of my dataset (stored as 1 partition). 

However... for the full dataset (multiple partitions) I run into an index issue because dask has an index per partition: 

```[python]

File ~/miniconda3/envs/coclico/lib/python3.10/site-packages/dask/base.py:292, in DaskMethodsMixin.compute(self, **kwargs)
    268 def compute(self, **kwargs):
    269     """Compute this dask collection
    270 
    271     This turns a lazy Dask collection into its in-memory equivalent.
   (...)
    290     dask.base.compute
    291     """
--> 292     (result,) = compute(self, traverse=False, **kwargs)
    293     return result

File ~/miniconda3/envs/coclico/lib/python3.10/site-packages/dask/base.py:575, in compute(traverse, optimize_graph, scheduler, get, *args, **kwargs)
    572     keys.append(x.__dask_keys__())
    573     postcomputes.append(x.__dask_postcompute__())
--> 575 results = schedule(dsk, keys, **kwargs)
    576 return repack([f(r, *a) for r, (f, a) in zip(results, postcomputes)])

File ~/miniconda3/envs/coclico/lib/python3.10/site-packages/dask/threaded.py:81, in get(dsk, result, cache, num_workers, pool, **kwargs)
     78     elif isinstance(pool, multiprocessing.pool.Pool):
     79         pool = MultiprocessingPoolExecutor(pool)
...
   4105 # trying to reindex on an axis with duplicates
   4106 if not self._index_as_unique and len(indexer):
-> 4107     raise ValueError("cannot reindex on an axis with duplicate labels")

``` 
Do you see another solution when dealing with multiple partitions? Thanks!

**Comment by giorgiobasile** [comment]
> We should probably add `dask_geopandas.from_wkt/from_wkb` functions as well, so you can do something similar when starting from a WKT / WKB column.

Hi @jorisvandenbossche, I'm pretty new to dask-geopandas. A few weeks back, I had a similar requirement and I basically ended up creating my own `from_wkt` and `from_wkb` functions, which I now shared [here](https://github.com/geopandas/dask-geopandas/commit/5cc149e3d9172f1410b77070ef7b46cda185f970).

I basically used the same approach implemented in `dask_geopandas.points_from_xy` to work with WKT/WKB geometries. I'm not sure whether you really find it useful to introduce these utilities; in that case, I'd be happy to send a PR.

**Comment by bkanuka** [comment]
None of the examples in this ticket worked for me, and it took me _way_ too long to figure out that it was because of dask-expr and its "query planning".  To get these examples to work, you need to disable query planning:
```
import dask

dask.config.set({"dataframe.query-planning": False})
```

See: https://github.com/geopandas/dask-geopandas/issues/284
