### ISSUE TITLE
Bug reading parquet files with `dask==2022.12.0`

### ISSUE THREAD

**Issue by the-matt-morris** [geopandas/dask-geopandas#225]
Hello, thanks for all the great work on this library!

I've been using this library as a dependency in one of my projects and just updated `dask` to `2022.12.0`.  With that change, I'm now receiving an error when I attempt to read a parquet file in from s3.  I have confirmed that this error exists with `dask==2022.12.0` but does not occur with `dask==2022.11.1`.  Using `dask_geopandas==0.2.0` on ubuntu 20.04.

Error:

```
>>> dgpd.read_parquet('s3://<MY_BUCKET>/boundaries.parquet')
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/dask/backends.py", line 125, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/parquet/core.py", line 479, in read_parquet
    read_metadata_result = engine.read_metadata(
  File "/usr/local/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 51, in read_metadata
    meta, stats, parts, index = super().read_metadata(fs, paths, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dask/dataframe/io/parquet/arrow.py", line 372, in read_metadata
    meta = cls._create_dd_meta(dataset_info, use_nullable_dtypes)
TypeError: _create_dd_meta() takes 2 positional arguments but 3 were given

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.9/site-packages/dask_geopandas/io/parquet.py", line 102, in read_parquet
    result = dd.read_parquet(*args, engine=GeoArrowEngine, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/dask/backends.py", line 127, in wrapper
    raise type(e)(
TypeError: An error occurred while calling the read_parquet method registered to the pandas backend.
Original Message: _create_dd_meta() takes 2 positional arguments but 3 were given
```

It seems it could be that because dask changed the function signature for [dask.dataframe.io.parquet.arrow::ArrowDatasetEngine._create_dd_meta](https://github.com/dask/dask/blob/2022.12.0/dask/dataframe/io/parquet/arrow.py#L983) and [dask_geopandas.io.parquet::GeoArrowEngine._create_dd_meta](https://github.com/geopandas/dask-geopandas/blob/91b5de706e44ffd71fccce475c1f6c1d1bbde841/dask_geopandas/io/parquet.py#L83) has not, this error occurs.

If needing to update that function is it, I can submit a PR to address this, taking into consideration the possibility for 2 different signatures based on the dask version being used.

**Comment by alejohz** [comment]
Encountered the same error and indeed `dask==2022.11.1` works for `dask-geopandas==0.2.0`. Thank you for creating this issue.

**Comment by martinfleis** [comment]
Thank you for the report!

> If needing to update that function is it, I can submit a PR to address this, taking into consideration the possibility for 2 different signatures based on the dask version being used.

That would be very welcome, thanks!

**Comment by martinfleis** [comment]
@jorisvandenbossche do you have any idea what needs to be done here? It seems that our usage of dask internals is not ideal.

**Comment by gerritholl** [comment]
Downgrading to dask 2022.11.1 also requires downgrading from Python 3.11 to Python 3.10, so this workaround doesn't work for people who have already upgraded to Python 3.11.

**Comment by jorisvandenbossche** [comment]
Sorry for the slow reply here! @the-matt-morris could you turn that branch into a PR? That will make it easier to discuss the details of the code changes

**Comment by the-matt-morris** [comment]
@jorisvandenbossche [PR created](https://github.com/geopandas/dask-geopandas/pull/230).  Unit tests for `3.11` fail in current state.  Let's continue the conversation over there.

**Comment by jorisvandenbossche** [comment]
The fix for this is released in https://github.com/geopandas/dask-geopandas/releases/tag/v0.3.0 !
