### ISSUE TITLE
0.2.1 release?

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/dask-geopandas#233]
Thanks @the-matt-morris and @jorisvandenbossche for fixing the read parquet fix (https://github.com/geopandas/dask-geopandas/pull/230).

Would it be possible for a release please?

I guess you may want to merge https://github.com/geopandas/dask-geopandas/pull/232 first?

**Comment by jorisvandenbossche** [comment]
Yes, I was indeed planning to do a new release, but indeed want to include https://github.com/geopandas/dask-geopandas/pull/232

**Comment by jorisvandenbossche** [comment]
Done! https://github.com/geopandas/dask-geopandas/releases/tag/v0.3.0

**Comment by raybellwaves** [comment]
Thank you very much
