### ISSUE TITLE
DOC: incomplete ipython cell

### ISSUE THREAD

**Issue by raybellwaves** [geopandas/dask-geopandas#239]
https://dask-geopandas.readthedocs.io/en/stable/guide/spatial-partitioning.html

shows
```
usa = geopandas.read_file(path, layer="ADM_1")
usa.head()
KeyboardInterrupt ...
```

**Comment by jsignell** [comment]
Hmm actually after taking a look I think that was a transient error and the solution is to rebuild the docs for stable. If you look at latest you can see that the layer does in fact exist: https://dask-geopandas.readthedocs.io/en/latest/guide/spatial-partitioning.html

**Comment by martinfleis** [comment]
I have triggered rebuild.
