### ISSUE TITLE
Drop distributed as a required dependency?

### ISSUE THREAD

**Issue by weiji14** [geopandas/dask-geopandas#258]
Continuing discussion from https://github.com/conda-forge/dask-geopandas-feedstock/pull/15#discussion_r1294298427 on whether [`distributed`](https://distributed.dask.org/en/stable/) should be a required dependency of dask-geopandas. Currently it is listed as required in setup.py at https://github.com/geopandas/dask-geopandas/blame/2d0abad32e324a494b34738ab70feb6d78cc0942/setup.py#L16

Looking at the git history, it seems like distributed has been listed as required since 2020 - 7a49aefb44dda954494feb902c9e9378be7372cd.

**Comment by BwL1289** [comment]
Pinging this thread.
