### ISSUE TITLE
Question regarding parallelism over many seperate GeoSeries

### ISSUE THREAD

**Issue by kurt-rhee** [geopandas/dask-geopandas#259]
Hello, 

Thank you for your awesome project.  I have a question where I have around 10,000 separate geoseries containing polygons.  For each of these geoseries I would like to perform a separate unary_union so that at the end I have 10,000 polygons one for each geoseries.

For example:
if geoseries_0 has three polygons A, B, C, and geoseries_1 has polygons D, E... I would like to return the unary union of ABC and the unary union of DE. 

Is it possible to do this in a parallel fashion? or is the parallelism only within a geoseries.

Thank you!

**Comment by TomAugspurger** [comment]
I don’t think that will be parallel. dask-geopandas, like dask.dataframe, parallelizes along the index so it well suited for long and not too wide data frames.

You might be able to use dask.delayed or dask.bag on a sequence of regular geopandas.GeoSeries to do your unary unions in parallel.

**Comment by kurt-rhee** [comment]
Understood thank you!
