### ISSUE TITLE
Check for `crs` before allowing `set_crs`

### ISSUE THREAD

**Issue by jsignell** [geopandas/dask-geopandas#3]
For `set_crs`, we probably want to check that the `crs` is None (not already set), and in that case raise a warning or error (maybe with a keyword to force it).

Otherwise I think people will accidentally call this assuming their geometries get transformed.

(we should also align with a similar method in GeoPandas)

Copied from: https://github.com/jsignell/dask-geopandas/pull/1/files/2953fe474021e53a364a58bc6f660c462a2d3c98#r394216055

**Comment by DahnJ** [comment]
I thought a bit about this. Wouldn't simply applying Geopandas' `set_crs` to the Dask GeoDataFrame's `_meta` do the trick? Something like:

```python
    def set_crs(self, value, allow_override=False):
        """Set the value of the crs on a new object"""
        meta = self._meta.set_crs(value, allow_override=allow_override)
        return self.map_partitions(_set_crs, value, meta=meta, enforce_metadata=False)
```

This way you follow what GeoPandas do and also get a check before calling `compute`. 

I tried quickly testing this locally and the function seems to work as expected. 

If you think this is going in the right direction, then I'll happily write a test or two and start a PR

**Comment by jsignell** [comment]
That sounds like a good approach to me. You might not even really need to set the meta ahead of time since `map_partitions` should emulate the function on `self._meta`

**Comment by DahnJ** [comment]
You're right, I think I found an easier way in #51.
