### ISSUE TITLE
Alpha release

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#30]
I know that there's still a lot to do before a first proper release but I was thinking that it would be helpful to do a tagged alpha release of a current state. Something like `0.0.1alpha1`. We are already using `dask-geopandas` in some of our research code and it would be helpful to pin a tagged version for reproducibility rather than install from git@master/commit.

Would it be okay for you? I am happy to prepare GitHub action to automatise release and conda recipe to have it on conda-forge as well.

**Comment by jorisvandenbossche** [comment]
Sorry for the late reply here. For me that would be good (@jsignell ?)

For automation we can probably copy the github action from geopandas you wrote. And already adding it as a feedstock to conda-forge will be useful for the future anyway.

**Comment by jsignell** [comment]
I am happy with the idea of an alpha release. I keep meaning to find time to come back to this. I think we can also ask to move it to the new dask-contrib org.

**Comment by martinfleis** [comment]
I'll push the release GitHub Action in a few days.

**Comment by jsignell** [comment]
> Wouldn't geopandas org be better in terms of long-term maintenance

Oh sure! Either one is fine with me.

**Comment by jorisvandenbossche** [comment]
Yeah, I was planning to ask you if we could move it to the geopandas org. Of course, the dask-contrib org would also be fine, but I think the "ties" are more tight with geopandas (both implementation and code integration wise, as (at the moment) the people working on it).

**Comment by jsignell** [comment]
Absolutely! @jorisvandenbossche you have ownership of it right? I am 100% on board with moving it under geopandas org.

**Comment by jorisvandenbossche** [comment]
I have commit rights here, but not enough admin rights on this repo to be able to transfer it (I don't see the "Settings" tab). 

But I am happy to add you to the geopandas team so you can transfer it (you need to keep access anyway)

**Comment by jsignell** [comment]
> I am happy to add you to the geopandas team

That'd be great! But I can also give you rights here. Whichever works better for the org structure.

**Comment by jsignell** [comment]
Ok so I will transfer this to geopandas org now!

**Comment by jsignell** [comment]
Hmmm 
![image](https://user-images.githubusercontent.com/4806877/109986388-b0239e00-7cd3-11eb-8f04-32e75cb1f05d.png)

**Comment by jorisvandenbossche** [comment]
Can you try again?

**Comment by jsignell** [comment]
I tried again and it still didn't work. I can probably transfer it to you @jorisvandenbossche if that works.

**Comment by jsignell** [comment]
Otherwise you could make me an owner for 2 min and then take it away again.

**Comment by jorisvandenbossche** [comment]
That's already the case ;) Maybe there is a bit of delay. Can you try again? And otherwise you can see if you can give me the rights here to let me transfer it

**Comment by jsignell** [comment]
Ok done!

**Comment by jorisvandenbossche** [comment]
Thanks!

**Comment by jorisvandenbossche** [comment]
OK, so we have a @geopandas/dask-team (for now just you, Martin and I) for this repo
