### ISSUE TITLE
spatial_shuffle fails when loading from a geopackage

### ISSUE THREAD

**Issue by RichardScottOZ** [geopandas/dask-geopandas#310]
e.g. https://github.com/geopandas/dask-geopandas/issues/302

Now, could this happen if you had shapefile data originally and saved as a geopackage?

**Comment by jorisvandenbossche** [comment]
This should be the same issue as in #302, which has been fixed now (and released: https://github.com/geopandas/dask-geopandas/releases/tag/v0.4.2), so closing this issue.
