### ISSUE TITLE
CI: expand CI and move it to GHA

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#35]
I think that we should expand CI to test on windows and mac and to include master versions of key packages. Since testing on windows/mac is not supported on Travis (maybe mac is if I remember?), I'd suggest to follow the geopandas model and switch to GitHub actions. 

Happy to do a PR.

**Comment by jorisvandenbossche** [comment]
We need to move away from Travis anyway, because it's only due the low activity the last months we don't run out of credits ;) (and let's at least have the intention to change the activity level! ;))

Yes, more or less copying the geopandas CI actions sounds good.

**Comment by jorisvandenbossche** [comment]
And we should certainly include pygeos in the env. Because in practice nobody should be using this package without pygeos I think ..
