### ISSUE TITLE
Provide expected shape for total_bounds

### ISSUE THREAD

**Issue by jsignell** [geopandas/dask-geopandas#4]
In principle, we know the shape of the returned array in `total_bounds`. It'd be nice if we could specify that to dask  (now you get a shape of `(nan, )`.

Copied from: https://github.com/jsignell/dask-geopandas/pull/1/files/2953fe474021e53a364a58bc6f660c462a2d3c98#r394208103

**Comment by martinfleis** [comment]
Closed by #75
