### ISSUE TITLE
Homepage doesn't exist?

### ISSUE THREAD

**Issue by jakirkham** [geopandas/dask-geopandas#41]
Not sure if this is expected, but the homepage listed in `setup.py` ( https://geopandas.dask.org/ ) doesn't seem to exist

https://github.com/geopandas/dask-geopandas/blob/610dd695d2cd69c9b05c1f53391ea17a688de470/setup.py#L32

**Comment by jorisvandenbossche** [comment]
Yes, thanks, that's indeed a wrong url
