### ISSUE TITLE
Announcement: workshop on scaling geospatial vector data during Dask Summit (Thursday May 20th)

### ISSUE THREAD

**Issue by jorisvandenbossche** [geopandas/dask-geopandas#45]
(Mis)using our issue tracker here for a moment, but I thought this was the easiest way to notify some people who have been trying out dask-geopandas / reporting issues / doing fixes, as this could potentially be interesting for you: @RichardScottOZ, @gansanay, @bilelomrani1, @njanakiev, @Rhiyo, @daviddemeij, @Guts, @deeplook

During the Dask Summit, we have a 2-hour workshop scheduled about scaling geospatial vector data on Thursday May 20th at 11-13:00 UTC (https://summit.dask.org/schedule/presentation/22/scaling-geospatial-vector-data/). All welcome to join!

See also https://github.com/geopandas/community/issues/4 for more details.

**Comment by RichardScottOZ** [comment]
Thanks!  Will see if I can manage the time! :)

**Comment by Guts** [comment]
Thanks! Interested but pretty sure I won't have enough time to participate.

**Comment by jorisvandenbossche** [comment]
We will probably have some recording / summary for those who can't join at that specific time.

**Comment by deeplook** [comment]
Thanks for the notice! I'll be there.

**Comment by njanakiev** [comment]
Thanks for sharing, I will try to join as well!

**Comment by martinfleis** [comment]
The recording of the workshop is available [here](https://zoom.us/rec/share/WFRbJZNlsdg49Oh1XxYmtheG2KTbL4-5AOj-_GuyBMjlLSQpabb0k2pbWPDgczmw.-F5hnexY3fEZ77_Z?startTime=1621508432000).

**Comment by daviddemeij** [comment]
Is the notebook used in the workshop available somewhere aswell?

**Comment by jorisvandenbossche** [comment]
Indeed, I put the notebook on a gist: https://gist.github.com/jorisvandenbossche/0d4091e29134e9e11c98075c3a110c2d#file-dask-geopandas-demo-ipynb

I should probably look into moving some of that into this repo (we have some example notebooks)
