### ISSUE TITLE
BUG: Failure with dask master

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#48]
This recent change https://github.com/dask/dask/pull/7586 removed `make_meta` from `dataframe.core` resulting in breakage of our implementation - https://github.com/geopandas/dask-geopandas/runs/2678080728?check_suite_focus=true

I've asked in that PR what is the best way to get around it but I also wanted to flag it here.

**Comment by jakirkham** [comment]
As mentioned in that PR ( https://github.com/rapidsai/cudf/pull/8368 ), this is how we are handling this in RAPIDS

Using `make_meta_util` works in place of `make_meta`, one can do `try...except...` to `import` one or the other based on Dask version
