### ISSUE TITLE
ImportError: cannot import name 'make_meta' from 'dask.dataframe.core'

### ISSUE THREAD

**Issue by hickskin** [geopandas/dask-geopandas#49]
As discussed in stackoverflow, could you update the library or any alternative solution, please.

https://stackoverflow.com/questions/67794640/importerror-cannot-import-name-make-meta-from-dask-dataframe-core

**Comment by jorisvandenbossche** [comment]
@martinfleis this was fixed in https://github.com/geopandas/dask-geopandas/pull/47 right? In that case we should probably do a quick release to have the released version working with the latest dask.

**Comment by martinfleis** [comment]
Yes.

**Comment by jorisvandenbossche** [comment]
OK, tagged master with alpha 3 -> https://github.com/geopandas/dask-geopandas/releases/tag/v0.1.0a3

It's already on PyPI, and will soon be on conda-forge as well.
