### ISSUE TITLE
ENH: repartition based on Geohash

### ISSUE THREAD

**Issue by tastatham** [geopandas/dask-geopandas#67]
Current spatial partitioning in Dask-GeoPandas is limited to computing convex hulls for a set of n arbitrarily defined partitions. 
Whilst a Dask-GeoDataFrame can be re-partitioned based on an attribute (column contained within the data) before computing the convex hull, this is dependent;
1. There being a suitable attribute
2. Data quality - assigning attributes to wrong geographic location, resulting in large convex hulls.
3. Defining the number of partitions

When dealing with Point data, an alternative approach is to encode each Point using the Geohash - which is a string that is both sortable and searchable based on prefixing.

### Advantages
* Fast to index
* Easy to interpret
* Useful for nearest-neighbour searches

### Disadvantages
* Limited to point data 
* Slow to compute - particularly for polygons
    - First identified by [SpatialPandas Scipy talk - vs HilbertRtree](https://github.com/Quansight/scipy2020_spatial_algorithms_at_scale/blob/master/spatial_algorithms_at_scale_presentation.pdf
)
    - Current packages are not optimised (e.g. the [Geohash package](https://github.com/vinsci/geohash) is 7 years old) and refactoring is being explored to improve this somewhat;
        + [Refactor Geohash package to numpy for points only](https://github.com/tastatham/gsoc_dask_geopandas_2021/issues/2)
        + [polygon_to_geohashes function in the Polygon Geohasher](https://github.com/tastatham/gsoc_dask_geopandas_2021/issues/3
)
* Geohash assumes points are projected in the world geodetic system crs (4326).
* Geohash package assumes a precision
    - To explore whether if the level of precision is not defined, to use some simple heuristic e.g. area
    -  If the geohash for the left/right geometries are already computed use the level of precision used.

In the next couple of weeks I will create a pull request with these features, as potential partitioning technique.

**Comment by jorisvandenbossche** [comment]
Is this closed by https://github.com/geopandas/dask-geopandas/pull/93?

**Comment by martinfleis** [comment]
I think so. @tastatham we can reopen if you think otherwise.
