### ISSUE TITLE
BUG: `shuffle` results in dask.DataFrame instead of GeoDataFrame

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#68]
Using `shuffle` on `dask_geopandas.GeoDataFrame` doesn't preserve the class and returns `dask.DataFrame` instead.

```py
gdf = geopandas.read_file(geopandas.datasets.get_path('naturalearth_lowres'))
ddf = dask_geopandas.from_geopandas(gdf, npartitions=4)
ddf.shuffle("continent")
```
![Screenshot 2021-07-06 at 21 20 55](https://user-images.githubusercontent.com/36797143/124661916-0f6f0600-dea0-11eb-8034-374a7c891bba.png)

**Comment by martinfleis** [comment]
I guess it is actually caused by the same issue as #59, passing `shuffle="tasks"` to `shuffle` returns GeoDataFrame.

**Comment by jorisvandenbossche** [comment]
Yes, I suppose that is indeed the same issue (since `set_index` also does a shuffle operation under the hood)

**Comment by martinfleis** [comment]
Closing as a duplicate then.
