### ISSUE TITLE
import dask_geopandas resulted “cannot import name '_nonempty_index' from 'dask.dataframe.utils' ”

### ISSUE THREAD

**Issue by katwynn** [geopandas/dask-geopandas#86]
while attempting to import dask_geopandas i encountered [error messages](https://stackoverflow.com/questions/68590444/import-dask-geopandas-resulted-cannot-import-name-nonempty-index-from-dask?noredirect=1#comment121223210_68590444) as following:

`import dask_geopandas Traceback (most recent call last): File "", line 1, in File "C:\Users\user\Miniconda3\envs\envname\lib\site-packages\dask_geopandas_init_.py", line 3, in from . import backends File "C:\Users\user\Miniconda3\envs\envname\lib\site-packages\dask_geopandas\backends.py", line 4, in from dask.dataframe.utils import ( ImportError: cannot import name '_nonempty_index' from 'dask.dataframe.utils' (C:\Users\user\Miniconda3\envs\envname\lib\site-packages\dask\dataframe\utils.py)`

apparently this name has moved from dask.dataframe.utils to dask.dataframe.backends. The initial underscore suggests it was not meant for use by other packages.

thank you

**Comment by martinfleis** [comment]
@katwynn Which versions of `dask` and `dask-geopandas` do you have? This should not be an issue with the latest versions of both.

**Comment by katwynn** [comment]
I have 
dask                      2021.7.1                 pypi_0    pypi
dask-core                 2021.7.1           pyhd8ed1ab_0    conda-forge
dask-geopandas            0.1.0a2            pyhd8ed1ab_0    conda-forge

**Comment by martinfleis** [comment]
Try `dask-geopandas 0.1.0a4`. If that doesn't work, we may need to do another release but I think it should. Otherwise, you can also install from git `pip install git+https://github.com/geopandas/dask-geopandas.git`.

**Comment by katwynn** [comment]
thank you, @martinfleis  installing from git worked perfectly

**Comment by martinfleis** [comment]
Great! I've opened #87 to change the code in a way that doesn't rely on private functions to avoid such a situation in the future.
