### ISSUE TITLE
REF: speed-up `calculate_spatial_partitions`

### ISSUE THREAD

**Issue by martinfleis** [geopandas/dask-geopandas#98]
`calculate_spatial_partitions` returns a single convex hull around all geometries in the partition. To do that, we currently create a convex hull of each geometry, union all using `unary_union` and create convex hull of that.

We don't need the first convex hull and union if we combine the partition into a single GeometryCollection and do the convex_hull of that.

Ideally, we should do this directly via pygeos but I am not sure we want to have pygeos as a hard dependency here (though everyone should use dask-geopandas with pygeos). The path via shapely also gives a speedup but pygeos can be 6x faster than that and 20x faster than the current implementation. See the timings below.

![Screenshot 2021-08-19 at 21 07 16](https://user-images.githubusercontent.com/36797143/130136716-5d1017b2-f5b7-4f14-96c1-9f5e0a7d7c5a.png)
 
Before I'll make a PR, I want to know if want to depend on pygeos and if there are some memory caveats in doing this (I don't think so). Thoughts?

**Comment by jorisvandenbossche** [comment]
Ah, that's a nice way to avoid the `unary_union` by turning it in a GeometryCollection (now I did the first convex_hull to make the unary_union somewhat less expensive ...)

Yeah, I think depending explicitly on pygeos is fine for now.
